### ISSUE TITLE
Node id

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#65]
With latest update in the code for node_id (association request), I see that node id is 0.0.0.0 instead of pfcp endpoint ip.
Is it problem in the configuration or something else ?

```
Message Type: PFCP Association Setup Response (6)
:
:
Node ID : IPv4 address: 0.0.0.0
    IE Type: Node ID (60)
    IE Length: 5
    0000 .... = Spare: 0
    .... 0000 = Node ID Type: IPv4 address (0)
    Node ID IPv4: 0.0.0.0
 ```

**Comment by RoadRunnr** [comment]
What version are you using?

The version from #52 needs a config like e.g.:

```
upf node-id ip4 172.1.1.1
```

Is doesn't pick up the node id from the PFCP endpoint.

**Comment by orion-belt** [comment]
I am using master branch actually.

**Comment by RoadRunnr** [comment]
> I am using master branch actually.

Master has not support for Node Id. That is what #52 will fix.

> And I think it is not implemented. Node id is mandatory in association message.

Yes it is and master is not correct in that respect at the moment.

> Just wonder why to set node id separately and not picking up pfcp endpoint ?

Because a UPF instance could have multiple PFCP endpoints or wants to be known by an ID that differs from its actual IP.

> 
> ```
> static void
> init_response_node_id (pfcp_node_id_t * node_id)
> {
>   //TODO: need CLI/API to set local Node-Id.....
> }
> ```
> 
> I used node id from request message as below -
> 
> ```
>   SET_BIT (resp.grp.fields, ASSOCIATION_PROCEDURE_RESPONSE_NODE_ID);
>   //init_response_node_id (&resp.node_id);
>   resp.node_id.ip = req->lcl.address;
> ```

`lcl.address` is copied directly from the VPP session layer. There could be problem in there somewhere.
